version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    target_branch: 'development'
    version_requirement_updates: 'increase_versions'
    commit_message:
      prefix: 'chore'
      include_scope: true
